version: '3.9'
services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - service-net
    healthcheck:
      test: [ "CMD-SHELL", "curl", "-f", "http://127.0.0.1:8080/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  service-net:
    driver: bridge